// Converts a short front-facing video into ASCII frames for talk/frames.js.
//
// Workflow (run locally, once — requires ffmpeg on PATH):
//   1. node scripts/make-frames.mjs dump face.mp4
//        → writes every frame as text into frames-dump/NNN.txt (browse them,
//          they're just text files)
//   2. Pick frames by number and assemble:
//        node scripts/make-frames.mjs build \
//          --neutral 12 --neutral2 30 --blink 45 --smile 88 \
//          --mouth 12,52,53,55
//        → overwrites talk/frames.js (same shape as the placeholder)
//
// Record tips: even lighting, plain background, face filling most of the
// frame, ~10s: hold neutral, blink twice, say one sentence, small smile.

import { execFileSync } from "node:child_process";
import { mkdirSync, readdirSync, readFileSync, writeFileSync, rmSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";

const COLS = 88;
const ROWS = 44;
const RAMP = " .:-=+*#%@";

const here = dirname(fileURLToPath(import.meta.url));
const root = join(here, "..");
const dumpDir = join(root, "frames-dump");

const [, , cmd, ...rest] = process.argv;

if (cmd === "dump") {
  const video = rest[0];
  if (!video) {
    console.error("Usage: node scripts/make-frames.mjs dump <video-file>");
    process.exit(1);
  }
  rmSync(dumpDir, { recursive: true, force: true });
  mkdirSync(dumpDir, { recursive: true });

  // 6 fps is plenty — blinks last ~150ms, so at least one frame catches them.
  // Grayscale, crop to centered square, scale to COLSxROWS. Terminal cells are
  // ~2x taller than wide, so ROWS is half of COLS to keep the face round.
  const rawDir = join(dumpDir, "raw");
  mkdirSync(rawDir);
  execFileSync("ffmpeg", [
    "-i", video,
    "-vf", `fps=6,format=gray,crop='min(iw,ih)':'min(iw,ih)',scale=${COLS}:${ROWS}`,
    "-f", "image2", "-vcodec", "pgm",
    join(rawDir, "%03d.pgm"),
  ], { stdio: "inherit" });

  // PGM (P5) → ASCII text files. Dark video pixel = ink = dense char, because
  // the site renders dark ink on paper.
  for (const f of readdirSync(rawDir).filter((f) => f.endsWith(".pgm")).sort()) {
    const buf = readFileSync(join(rawDir, f));
    const ascii = pgmToAscii(buf);
    writeFileSync(join(dumpDir, f.replace(".pgm", ".txt")), ascii.join("\n") + "\n");
  }
  rmSync(rawDir, { recursive: true, force: true });
  console.log(`Dumped frames to frames-dump/ — open the .txt files and pick your frames.`);
} else if (cmd === "build") {
  const args = {};
  for (let i = 0; i < rest.length; i += 2) args[rest[i].replace(/^--/, "")] = rest[i + 1];
  const need = ["neutral", "neutral2", "blink", "smile", "mouth"];
  for (const k of need) {
    if (!args[k]) {
      console.error(`Missing --${k}. Usage: build --neutral N --neutral2 N --blink N --smile N --mouth N,N,N,N`);
      process.exit(1);
    }
  }
  const load = (n) =>
    readFileSync(join(dumpDir, `${String(n).padStart(3, "0")}.txt`), "utf8")
      .replace(/\n$/, "")
      .split("\n");

  const frames = {
    cols: COLS,
    rows: ROWS,
    ramp: RAMP,
    placeholder: false,
    neutral: load(args.neutral),
    neutral2: load(args.neutral2),
    blink: load(args.blink),
    smile: load(args.smile),
    mouth: args.mouth.split(",").map((n) => load(n.trim())),
  };
  const out = `// Generated by scripts/make-frames.mjs — do not hand-edit.\nexport const FRAMES = ${JSON.stringify(frames)};\n`;
  writeFileSync(join(root, "talk", "frames.js"), out);
  console.log("Wrote talk/frames.js from real video frames.");
} else {
  console.error("Usage: make-frames.mjs dump <video> | build --neutral N --neutral2 N --blink N --smile N --mouth N,N,N,N");
  process.exit(1);
}

function pgmToAscii(buf) {
  // Minimal P5 parser: magic, whitespace-separated width/height/maxval, raster.
  const text = buf.toString("latin1");
  const m = /^P5\s+(?:#[^\n]*\n\s*)?(\d+)\s+(\d+)\s+(\d+)\s/.exec(text);
  if (!m) throw new Error("Not a binary PGM (P5) file");
  const [, w, h, maxval] = m.map(Number);
  const offset = m[0].length;
  const rows = [];
  for (let y = 0; y < h; y++) {
    let row = "";
    for (let x = 0; x < w; x++) {
      const lum = buf[offset + y * w + x] / maxval; // 0 dark … 1 light
      const ink = 1 - lum; // dark pixel → dense char
      row += RAMP[Math.min(RAMP.length - 1, Math.floor(ink * (RAMP.length - 1) + 0.001))];
    }
    rows.push(row);
  }
  return rows;
}
