// Rebuild just the mouth visemes in talk/frames.js from the neutral portrait.
// No art source needed — run after tweaking scripts/mouth-shapes.mjs.
//
//   node scripts/regen-mouth.mjs

import { readFileSync, writeFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { charsToInk, inkToChars, buildMouthFrames, MOUTH } from "./mouth-shapes.mjs";

const here = dirname(fileURLToPath(import.meta.url));
const framesPath = join(here, "..", "talk", "frames.js");
const src = readFileSync(framesPath, "utf8");
const match = src.match(/export const FRAMES = (\{.*\});/s);
if (!match) {
  console.error("Could not parse talk/frames.js");
  process.exit(1);
}

const FRAMES = JSON.parse(match[1]);
const grid = charsToInk(FRAMES.neutral, FRAMES.ramp);
FRAMES.mouth = buildMouthFrames(grid, MOUTH).map((g) => inkToChars(g, FRAMES.ramp));

writeFileSync(
  framesPath,
  `// Generated by scripts/make-frames-from-art.mjs; mouth visemes via scripts/regen-mouth.mjs.\nexport const FRAMES = ${JSON.stringify(FRAMES)};\n`,
);

// Quick visual dump of the mouth region for sanity-checking shapes.
for (let i = 0; i < FRAMES.mouth.length; i++) {
  console.log(`--- mouth ${i}`);
  for (let y = 48; y <= 58; y++) console.log(String(y).padStart(2), FRAMES.mouth[i][y].slice(35, 65));
}
console.log(`Wrote ${FRAMES.mouth.length} mouth frames → talk/frames.js`);
